[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = '0'
rev = 'master'
hook_source = 'call coil398#init#coc#hook_source()'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repo = 'fatih/vim-go'
